    version: '3.8'  

    services:
        backend:
            build: ./ChatApp.API
            volumes:
                - ./ChatApp.API:/usr/src/app
            ports:
                - 5085:8080
            environment:
                - ASPNETCORE_ENVIRONMENT=Development
        frontend:
            build: ./BlazorChatWasm
            ports:
                - 5228:80
            depends_on:
                - backend
          

        

          